[2024-06-04T14:56:34.048-0300] {scheduler_job_runner.py:769} ERROR - Executor reports task instance <TaskInstance: meu_dag.Cria_pasta scheduled__2024-06-03T00:00:00+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
